### ISSUE TITLE
multi-cursor への対応

### ISSUE THREAD

**Issue by knoajp** [susisu/move-cursor-improved#1]
デフォルトの仕様に不便を感じていましたが、move-cursor-improved のおかげでとても快適になりました。

multi-cursor に対応していただけると、ますます助かります。
https://atom.io/packages/multi-cursor

ご検討いただければ幸いです。

**Comment by susisu** [comment]
ありがとうございます.

カーソルを上下の行に複製するだけであればすでに対応しています (ドキュメントが不親切ですみません).
以下のような設定を keymap に追記してみてください.

``` coffee
'atom-workspace atom-text-editor:not(.mini)':
  'alt-down': 'move-cursor-improved:add-next-line'
  'alt-up'  : 'move-cursor-improved:add-previous-line'
```

その他のコマンド (おそらく「最後に追加されたカーソルを移動」のみ?) は必要であれば実装しようと思いますが, どうでしょう?

---

Thank you.

There already exist commands for adding a cursor to previous/next line (sorry for the poor documentation).
This keymap will help:

``` coffee
'atom-workspace atom-text-editor:not(.mini)':
  'alt-down': 'move-cursor-improved:add-next-line'
  'alt-up'  : 'move-cursor-improved:add-previous-line'
```

I will implement other commands in the multi-cursor package if needed.
How do you think?

**Comment by knoajp** [comment]
ご案内ありがとうございます。
ヒジョーに、ますます、快適になりました！
個人的にはこれで十分理想的な状態になりました。
(正直「最後に追加されたカーソルを移動」が何を意味するのかピンと来ていません)

わたしと同じように「multi-cursor に対応していたらいいのに…」と思っているひとが、まだいる気がしますので、README.md にでも "If you use multi-cursor package, this keymap.cson may help you." みたいな感じでコードを貼ってあげてほしいと思いました。

**Comment by susisu** [comment]
ご指摘を受けて README を更新しました.
ありがとうございます.

---

I updated README. Thanks for your advice!
